"""Initial Migration

Revision ID: d8bd50860fc1
Revises: None
Create Date: 2016-09-07 00:25:40.484133

"""

# revision identifiers, used by Alembic.
revision = 'd8bd50860fc1'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('meeting_action_item_priority',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.Column('updated_date', sa.DateTime(), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_meeting_action_item_priority_created_date'), 'meeting_action_item_priority', ['created_date'], unique=False)
    op.create_index(op.f('ix_meeting_action_item_priority_updated_date'), 'meeting_action_item_priority', ['updated_date'], unique=False)
    op.create_table('meeting_action_item_status',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.Column('updated_date', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_meeting_action_item_status_created_date'), 'meeting_action_item_status', ['created_date'], unique=False)
    op.create_index(op.f('ix_meeting_action_item_status_updated_date'), 'meeting_action_item_status', ['updated_date'], unique=False)
    op.create_table('people',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.Column('updated_date', sa.DateTime(), nullable=True),
    sa.Column('first_name', sa.Text(), nullable=True),
    sa.Column('last_name', sa.Text(), nullable=True),
    sa.Column('location', sa.Text(), nullable=True),
    sa.Column('start_date', sa.DateTime(), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_people_created_date'), 'people', ['created_date'], unique=False)
    op.create_index(op.f('ix_people_updated_date'), 'people', ['updated_date'], unique=False)
    op.create_table('meetings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.Column('updated_date', sa.DateTime(), nullable=True),
    sa.Column('person_id', sa.Integer(), nullable=True),
    sa.Column('start_date', sa.DateTime(), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['person_id'], ['people.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_meetings_created_date'), 'meetings', ['created_date'], unique=False)
    op.create_index(op.f('ix_meetings_updated_date'), 'meetings', ['updated_date'], unique=False)
    op.create_table('people_goals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.Column('updated_date', sa.DateTime(), nullable=True),
    sa.Column('person_id', sa.Integer(), nullable=True),
    sa.Column('goal', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['person_id'], ['people.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_people_goals_created_date'), 'people_goals', ['created_date'], unique=False)
    op.create_index(op.f('ix_people_goals_updated_date'), 'people_goals', ['updated_date'], unique=False)
    op.create_table('meeting_action_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.Column('updated_date', sa.DateTime(), nullable=True),
    sa.Column('meeting_id', sa.Integer(), nullable=True),
    sa.Column('status_id', sa.Integer(), nullable=True),
    sa.Column('priority_id', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('due_date', sa.DateTime(), nullable=True),
    sa.Column('completed_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['meeting_id'], ['meetings.id'], ),
    sa.ForeignKeyConstraint(['priority_id'], ['meeting_action_item_priority.id'], ),
    sa.ForeignKeyConstraint(['status_id'], ['meeting_action_item_status.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_meeting_action_items_created_date'), 'meeting_action_items', ['created_date'], unique=False)
    op.create_index(op.f('ix_meeting_action_items_updated_date'), 'meeting_action_items', ['updated_date'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_meeting_action_items_updated_date'), table_name='meeting_action_items')
    op.drop_index(op.f('ix_meeting_action_items_created_date'), table_name='meeting_action_items')
    op.drop_table('meeting_action_items')
    op.drop_index(op.f('ix_people_goals_updated_date'), table_name='people_goals')
    op.drop_index(op.f('ix_people_goals_created_date'), table_name='people_goals')
    op.drop_table('people_goals')
    op.drop_index(op.f('ix_meetings_updated_date'), table_name='meetings')
    op.drop_index(op.f('ix_meetings_created_date'), table_name='meetings')
    op.drop_table('meetings')
    op.drop_index(op.f('ix_people_updated_date'), table_name='people')
    op.drop_index(op.f('ix_people_created_date'), table_name='people')
    op.drop_table('people')
    op.drop_index(op.f('ix_meeting_action_item_status_updated_date'), table_name='meeting_action_item_status')
    op.drop_index(op.f('ix_meeting_action_item_status_created_date'), table_name='meeting_action_item_status')
    op.drop_table('meeting_action_item_status')
    op.drop_index(op.f('ix_meeting_action_item_priority_updated_date'), table_name='meeting_action_item_priority')
    op.drop_index(op.f('ix_meeting_action_item_priority_created_date'), table_name='meeting_action_item_priority')
    op.drop_table('meeting_action_item_priority')
    ### end Alembic commands ###
